# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ERIC Documentation
author: Christian Foerster - rdm@eawag.ch
logo: _static/images/light_logo.png
copyright: "2024"

bibtex_bibfiles: 
  - sources.bib

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/eawag-rdm/eric-documentation  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: _static/images/favicon-96x96.png
  home_page_in_navbar: false
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    html_theme_options: 
      logo:
        image_light: _static/images/light_logo.png
        image_dark: _static/images/dark_logo.png
    

